Adapt flow-execute

diff --git a/bin/flow-execute b/bin/flow-execute
--- a/bin/flow-execute
+++ b/bin/flow-execute
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+export HOME=`getent passwd $USER | cut -d':' -f6`
+source ~/.bashrc
+
 echo "Executing on $CLUSTER"
 
 if [ "$CLUSTER" = "cedar" ]
@@ -32,13 +35,14 @@ then
     exit 1
 fi
 
-echo "Data folder: ${DATA_FOLDER}"
+echo "Data folder: ${CONTAINER_DATA}"
 
-if [ ! -d "${DATA_FOLDER}" ]
+if [ ! -d "${CONTAINER_DATA}" ]
 then
-    mkdir -p ${DATA_FOLDER}
+    mkdir -p ${CONTAINER_DATA}
 fi
 
+# Replace : by - in pathname
 CONTAINER_HOME=${CONTAINER_HOME//[:]/-}
 
 echo "Container home: ${CONTAINER_HOME}"
@@ -51,10 +55,16 @@ else
     echo "${CONTAINER_HOME}/${USER} already exists"
 fi
 
-echo "Config dir: ${EXEC_CONFIG}"
-if [ ! -d "${EXEC_CONFIG}" ]
+if [ -z "${CONTAINER_CONFIG}" ]
 then
-    mkdir -p ${EXEC_CONFIG}
+    echo 'Error: Please set $CONTAINER_CONFIG'
+    exit 1
+fi
+
+echo "Config dir: ${CONTAINER_CONFIG}"
+if [ ! -d "${CONTAINER_CONFIG}" ]
+then
+    mkdir -p ${CONTAINER_CONFIG}
 fi
 
 # cp -r ${HOME}/.config ${CONTAINER_HOME}/${USER}/
@@ -62,8 +72,8 @@ fi
 # run
 SINGULARITYENV_DATA_PATH=/data \
     singularity exec \
-        --bind ${EXEC_CONFIG}/:/config \
+        --bind ${CONTAINER_CONFIG}/:/config \
         --bind ${CERTIFICATE_FOLDER}/:/certs \
-        --bind ${DATA_FOLDER}/:/data \
+        --bind ${CONTAINER_DATA}/:/data \
         --bind ${CONTAINER_HOME}/:/home \
         --nv $(sregistry get $1) ${@:2}
