Set bind paths
Why:

Container needs paths to;
- data folder to avoid downloading data for each trial.
- experiment folder; to keep saved models
- certificate folder; because we don't want that certificate in the
container for security reasons.

diff --git a/bin/flow-execute b/bin/flow-execute
--- a/bin/flow-execute
+++ b/bin/flow-execute
@@ -1,29 +1,40 @@
 #!/usr/bin/env bash
 
-if [ "$cluster" = "cedar" ]
+echo "Executing on $CLUSTER"
+
+if [ "$CLUSTER" = "cedar" ]
 then
     module load 'singularity/2.4'
     CONTAINER_HOME=$SCRATCH/$1
-elif [ "$cluster" = "graham" ]
+elif [ "$CLUSTER" = "graham" ]
 then
     module load 'singularity/2.4'
     CONTAINER_HOME=$SCRATCH/$1
+else
+    echo "ERROR: unknown cluster"
+    exit 1
 fi
 
 # Pull only if it exists
 sregistry pull $1
 
 # Prepare mountings
-if [ ${CERTIFICATE_FOLDER} -z ]
+echo "Certificate folder: ${CERTIFICATE_FOLDER}"
+
+if [ -z "${CERTIFICATE_FOLDER}" ]
 then
     echo 'Error: certificate folder not defined. Please set $CERTIFICATE_FOLDER'
     exit 1
 fi
 
+echo "Data folder: ${DATA_FOLDER}"
+
 if [ ! -d "${DATA_FOLDER}" ]
 then
     mkdir -p ${DATA_FOLDER}
 fi
+
+echo "Container home: ${CONTAINER_HOME}"
 
 if [ ! -d "${CONTAINER_HOME}" ]
 then
@@ -31,8 +42,9 @@ then
 fi
 
 # run
-singularity exec --nv \
-    --bind ${CERTIFICATE_FOLDER}/:/certs \
-    --bind ${DATA_FOLDER}/:/data \
-    --bind ${CONTAINER_HOME}/:/home \
-    --nv $(sregistry get $1) ${@:2}
+SINGULARITYENV_DATA_PATH=/data \
+    singularity exec \
+        --bind ${CERTIFICATE_FOLDER}/:/certs \
+	--bind ${DATA_FOLDER}/:/data \
+	--bind ${CONTAINER_HOME}/:/home \
+	--nv $(sregistry get $1) ${@:2}
